name: Test Action

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    - name: Build latest dist/ folder
      run: |
        npm ci
        npm run build
    - name: Upload dist/ folder
      run: |
        git config --global user.email "<41898282+github-actions[bot]@users.noreply.github.com>"
        git config --global user.name "github-actions[bot]"
        git checkout --orphan ci
        git add -f dist README.md LICENSE action.yaml
        git commit -m "chore: create ci release ($GITHUB_SHA)"
        git push -f origin ci
  test:
    name: Test
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Setup tale/kubectl-action
      uses: tale/kubectl-action@ci
      with:
        base64-kube-config: ${{ secrets.KUBE_CONFIG }}
    - name: Test the output of `kubectl cluster-info`
      run: kubectl cluster-info
